src/CommandCenter/Controllers/LandingPageController.cs
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace CommandCenter.Controllers
{
    using System;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading;
    using System.Threading.Tasks;
    using CommandCenter.Authorization;
    using CommandCenter.Marketplace;
    using CommandCenter.Models;
    using Microsoft.AspNetCore.Authentication.OpenIdConnect;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Logging;
    using Microsoft.Extensions.Options;
    using Microsoft.Marketplace.SaaS;
    using Microsoft.Marketplace.SaaS.Models;

    /// <summary>
    /// Landing page.
    /// </summary>
    [Authorize(AuthenticationSchemes = OpenIdConnectDefaults.AuthenticationScheme)]
    // Specify the auth scheme to be used for logging on users. This is for supporting WebAPI auth
    
    public class LandingPageController : Controller
    {
        private readonly ILogger<LandingPageController> logger;
        private readonly IMarketplaceProcessor marketplaceProcessor;
        private readonly IMarketplaceNotificationHandler notificationHandler;
        private readonly IMarketplaceSaaSClient marketplaceClient;
        private readonly CommandCenterOptions options;

        /// <summary>
        /// Initializes a new instance of the <see cref="LandingPageController"/> class.
        /// </summary>
        /// <param name="commandCenterOptions">Options.</param>
        /// <param name="marketplaceProcessor">Marketplace processor.</param>
        /// <param name="notificationHandler">Notification handler.</param>
        /// <param name="marketplaceClient">Marketplace client.</param>
        /// <param name="logger">Logger.</param>
        public LandingPageController(
            IOptionsMonitor<CommandCenterOptions> commandCenterOptions,
            IMarketplaceProcessor marketplaceProcessor,
            IMarketplaceNotificationHandler notificationHandler,
            IMarketplaceSaaSClient marketplaceClient,
            ILogger<LandingPageController> logger)
        {
            if (commandCenterOptions == null)
            {
                throw new ArgumentNullException(nameof(commandCenterOptions));
            }

            this.marketplaceProcessor = marketplaceProcessor;
            this.notificationHandler = notificationHandler;
            this.marketplaceClient = marketplaceClient;
            this.logger = logger;
            this.options = commandCenterOptions.CurrentValue;
        }

        /// <summary>
        /// Landing page get.
        /// </summary>
        /// <param name="token">Marketplace purchase identification token.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>Action result.</returns>
        public async Task<ActionResult> Index(string token, CancellationToken cancellationToken)
        {
            if (string.IsNullOrEmpty(token))
            {
                this.ModelState.AddModelError(string.Empty, "Token URL parameter cannot be empty");
                this.ViewBag.Message = "Token URL parameter cannot be empty";
                return this.View();
            }

            // Get the subscription for the offer from the marketplace purchase identification token
            var resolvedSubscription = await this.marketplaceProcessor.GetSubscriptionFromPurchaseIdentificationTokenAsync(token, cancellationToken).ConfigureAwait(false);

            // Rest is implementation detail. In this sample, we chose allow the subscriber to change the plan for an activated subscriptio
            if (resolvedSubscription == default(ResolvedSubscription))
            {
                this.ViewBag.Message = "Token did not resolve to a subscription";
                return this.View();
            }

            // resolvedSubscription.Subscription is null when calling mock endpoint
            var existingSubscription = resolvedSubscription.Subscription;

            var availablePlans = await this.marketplaceClient.Fulfillment.ListAvailablePlansAsync(
                resolvedSubscription.Id.Value,
                null,
                null,
                cancellationToken).ConfigureAwait(false);

            var pendingOperations = await this.marketplaceClient.Operations.ListOperationsAsync(
                resolvedSubscription.Id.Value,
                null,
                null,
                cancellationToken).ConfigureAwait(false);

            var provisioningModel = new AzureSubscriptionProvisionModel
            {
                PlanId = resolvedSubscription.PlanId,
                SubscriptionId = resolvedSubscription.Id.Value,
                OfferId = resolvedSubscription.OfferId,
                SubscriptionName = resolvedSubscription.SubscriptionName,
                PurchaserEmail = existingSubscription?.Purchaser?.EmailId,
                PurchaserTenantId = existingSubscription?.Purchaser?.TenantId ?? Guid.Empty,

                // Assuming this will be set to the value the customer already set when subscribing, if we are here after the initial subscription activation
                // Landing page is used both for initial provisioning and configuration of the subscription.
                Region = TargetContosoRegionEnum.NorthAmerica,
                AvailablePlans = availablePlans?.Value.Plans.ToList(),
                SubscriptionStatus = existingSubscription?.SaasSubscriptionStatus ?? SubscriptionStatusEnum.NotStarted,
                PendingOperations = pendingOperations?.Value.Operations?.Any(o => o.Status == OperationStatusEnum.InProgress) ?? false,
            };

            if (provisioningModel != default)
            {
                provisioningModel.FullName = (this.User.Identity as ClaimsIdentity)?.FindFirst("name")?.Value;
                provisioningModel.Email = this.User.Identity.GetUserEmail();
                provisioningModel.BusinessUnitContactEmail = this.User.Identity.GetUserEmail();

                return this.View(provisioningModel);
            }

            this.ModelState.AddModelError(string.Empty, "Cannot resolve subscription");
            return this.View();
        }

        /// <summary>
        /// Landing page post handler.
        /// </summary>
        /// <param name="provisionModel">View model.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>Action result.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(AzureSubscriptionProvisionModel provisionModel, CancellationToken cancellationToken)
        {
            if (provisionModel == null)
            {
                throw new ArgumentNullException(nameof(provisionModel));
            }

            var urlBase = $"{this.Request.Scheme}://{this.Request.Host}";
            this.options.BaseUrl = new Uri(urlBase);
            try
            {
                // A new subscription will have PendingFulfillmentStart as status
                if (provisionModel.SubscriptionStatus == SubscriptionStatusEnum.PendingFulfillmentStart)
                {
                    await this.notificationHandler.ProcessNewSubscriptionAsyc(provisionModel, cancellationToken).ConfigureAwait(false);
                }
                else
                {
                    await this.notificationHandler.ProcessChangePlanAsync(provisionModel, cancellationToken).ConfigureAwait(false);
                }

                return this.RedirectToAction(nameof(this.Success));
            }
            catch (Exception ex)
            {
                return this.BadRequest(ex);
            }
        }

        /// <summary>
        /// Success.
        /// </summary>
        /// <returns>Action result.</returns>
        public ActionResult Success()
        {
            return this.View();
        }
    }
}

src/CommandCenter/Views/LandingPage/Index.cshtml
@using Microsoft.Marketplace.SaaS.Models
@using CommandCenter.Models
@model CommandCenter.Models.AzureSubscriptionProvisionModel

@{
    ViewData["Title"] = "Index";
}

<h1>Configure subscription</h1>

@if (Model == default)
{
    <span class="text-danger">@ViewBag.message, please check logs.</span>
}
else
{
    <p>The publisher can design a form like below to capture information from the subscriber to kick off the onboarding process for the new customer.</p>

    <hr />

    <span class="text-danger">@Html.ValidationSummary(false)</span>

    <form asp-controller="LandingPage" asp-action="Index">
        <div class="container">
            <dl class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="row">
                            <div class="col-sm-3">
                                @Html.DisplayNameFor(model => model.Email)
                            </div>
                            <div class="col-sm-9">
                                @Html.DisplayFor(model => model.Email)
                                <input asp-for="Email" type="hidden" class="form-control" />
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-3">
                                @Html.DisplayNameFor(model => model.FullName)
                            </div>
                            <div class="col-sm-9">
                                @Html.DisplayFor(model => model.FullName)
                                <input asp-for="FullName" type="hidden" class="form-control" />
                            </div>
                        </div>

                    </div>

                    <div class="panel panel-default">

                        <div class="row">
                            <div class="col-sm-3">
                                @Html.DisplayNameFor(model => model.OfferId)
                            </div>
                            <div class="col-sm-9">
                                @Html.DisplayFor(model => model.OfferId)
                                <input asp-for="OfferId" type="hidden" class="form-control" />
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-3">
                                @Html.DisplayNameFor(model => model.PlanId)
                            </div>
                            <div class="col-sm-9">
                                @Html.DisplayFor(model => model.PlanId)
                                <input asp-for="PlanId" type="hidden" class="form-control" />
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-3">
                                @Html.DisplayNameFor(model => model.PurchaserEmail)
                            </div>
                            <div class="col-sm-9">
                                @Html.DisplayFor(model => model.PurchaserEmail)
                                <input asp-for="PurchaserEmail" type="hidden" class="form-control" />
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-3">
                                @Html.DisplayNameFor(model => model.PurchaserTenantId)
                            </div>
                            <div class="col-sm-9">
                                @Html.DisplayFor(model => model.PurchaserTenantId)
                                <input asp-for="PurchaserTenantId" type="hidden" class="form-control" />
                            </div>
                        </div>

                        @if (Model.SubscriptionStatus == SubscriptionStatusEnum.Subscribed)
                        {
                            <div class="row">
                                <div class="col-sm-3">
                                    @Html.DisplayNameFor(model => model.AvailablePlans)
                                </div>

                                <div class="col-sm-9">

                                    <select asp-for="NewPlanId" asp-items="@(new SelectList(Model.AvailablePlans, "PlanId", "DisplayName"))" class="form-control">
                                        <option value="">Choose a new plan, or plan you wish to be on.</option>
                                    </select>
                                </div>
                            </div>
                        }

                        <div class="row">
                            <div class="col-sm-3">
                                @Html.DisplayNameFor(model => model.SubscriptionId)
                            </div>
                            <div class="col-sm-9">
                                @Html.DisplayFor(model => model.SubscriptionId)
                                <input asp-for="SubscriptionId" type="hidden" class="form-control" />
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-3">
                                @Html.DisplayNameFor(model => model.SubscriptionName)
                            </div>
                            <div class="col-sm-9">
                                @Html.DisplayFor(model => model.SubscriptionName)
                                <input asp-for="SubscriptionName" type="hidden" class="form-control" />
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="row">
                            <div class="col-sm-3">
                                @Html.DisplayNameFor(model => model.Region)
                            </div>
                            <div class="col-sm-3">
                                <select asp-for="Region" asp-items="Html.GetEnumSelectList<TargetContosoRegionEnum>()" class="form-control">
                                    <option selected="selected" value="">Please select</option>
                                </select>
                            </div>
                            <div class="col-sm-9"></div>
                        </div>

                        <div class="row">
                            <div class="col-sm-3">
                                @Html.DisplayNameFor(model => model.BusinessUnitContactEmail)
                            </div>
                            <div class="col-sm-9">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <input asp-for="BusinessUnitContactEmail" type="email" class="form-control" />
                                    </div>
                                    <div class="col-sm-9">
                                        <p>*The purchaser (who sees this page) can be different than the actual user of the solution.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </dl>
            @* Just to carry over the subscription status, so we can determine if we are here for initial
                provisioning or configuration later in the life of the subscription*@
            <input asp-for="SubscriptionStatus" type="hidden" class="form-control" />
        </div>
        <div>
            <input type="submit"
                   value="Submit"
                   class="btn btn-primary" />
        </div>
    </form>
}

src/CommandCenter/Views/LandingPage/Success.cshtml
@{
    ViewData["Title"] = "Success";
}

<h1>Success</h1>

Your request has been recorded. A member of the operations team will contact shortly.